# constants.py
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
PLAYER_RADIUS = 20
WHITE = (255, 255, 255)
PLAYER_TURN_SPEED = 300  # Radians per second
PLAYER_SPEED = 200  # Pixels per second
SHOT_RADIUS = 5  # Radius of a bullet
PLAYER_SHOOT_SPEED = 500  # Speed of a bullet
PLAYER_SHOOT_COOLDOWN = 0.3  # Cooldown time in seconds